// <auto-generated />
using System;
using MInReact.CarDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MInReact.Migrations
{
    [DbContext(typeof(CarDbContext))]
    partial class CarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MInReact.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("Marke")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int?>("MarkeId");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("ProductionYear");

                    b.HasKey("Id");

                    b.HasIndex("MarkeId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("MInReact.Models.Marke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Markes");
                });

            modelBuilder.Entity("MInReact.Models.Car", b =>
                {
                    b.HasOne("MInReact.Models.Marke")
                        .WithMany("Cars")
                        .HasForeignKey("MarkeId");
                });
#pragma warning restore 612, 618
        }
    }
}
